<?php
/**
 * Executes all cron tabs and cron jobs as a standalone process
 *
 * Example usage:
 *   /usr/local/bin/php -q /home/YOUR_USERNAME/public_html/modules/core/cron.php
 */
chdir(dirname(__FILE__));
$APP_CONF = array();
$Phpr_InitOnly = true;
include '../../index.php';

Core_Cron::execute_cron();


/*
 * WARNING: DO NOT EDIT THIS FILE.
 * Changes to the script will be reset by future updates.
 * Set up custom cron executions by copying this file to a new filename.
 * Eg.
 * File: /modules/core/cron_x.php
 * Usage:  /usr/local/bin/php -q /home/YOUR_USERNAME/public_html/modules/core/cron_x.php
 *
 * Execution examples below.
 */



/*
 * EXECUTE CRON JOBS ONLY
 */

//Core_Cron::$cronjob_batch_size = 10;
//Core_Cron::$cronjob_batch_shuffle = false;
//Core_Cron::$tracelog_events = true;
//$process_tabs = false;
//$process_que = true;
//Core_Cron::execute_cron($process_tabs, $process_que);


/*
 * EXECUTE CRON JOBS IN SPECIFIC QUE NAME
 */

//Core_Cron::$cronjob_batch_size = 100;
//Core_Cron::$cronjob_batch_shuffle = true;
//Core_Cron::$tracelog_events = true;
//$process_tabs = false;
//$process_que = 'notifications';
//Core_Cron::execute_cron($process_tabs, $process_que);


/*
 * EXECUTE CRON TAB ONLY
 */

//Core_Cron::$tracelog_events = true;
//$process_tabs = true;
//$process_jobs = false;
//Core_Cron::execute_cron($process_tabs, $process_jobs);