<?php
/**
 * Executes all cron tabs and cron jobs as a standalone process
 *
 * Example usage:
 *   /usr/local/bin/php -q /home/YOUR_USERNAME/public_html/modules/core/cron.php
 *
 * Optional command line parameters
 * j: job execution limit
 * s: cron execution time limit in seconds
 * q: job que name to execute. NULL for all, 0 for none.
 * t: process cron tabs .  1 or 0
 *
 * Example usage with parameters:
 *   /usr/local/bin/php -q /home/YOUR_USERNAME/public_html/modules/core/cron.php -j5 -s3600 -qpriority -t0
 */
chdir(dirname(__FILE__));
$APP_CONF = array();
$Phpr_InitOnly = true;
include '../../index.php';

//Defaults
$process_tabs = true;
$process_que = true;
Core_Cron::$execute_cron_time_limit_seconds = 4500;

//Command line params
$params = getopt("j:s:q:t:");
$job_limit = isset($params['j']) ? $params['j'] : null;
$time_limit = isset($params['s']) ? $params['s'] : null;
$que = isset($params['q']) ? $params['q'] : null;
$tabs = isset($params['t']) ? $params['t'] : null;


if(is_numeric($job_limit)) {
	Core_Cron::$cronjob_batch_size = $job_limit;
}
if(is_numeric($time_limit) ) {
	Core_Cron::$execute_cron_time_limit_seconds = $time_limit;
	@set_time_limit($time_limit);  // script limit
}
if($tabs !== null) {
	$process_tabs = $tabs ? true : false;
}
if($que !== null){
	$process_que = $que ? $que : false;
}

Core_Cron::execute_cron($process_tabs,$process_que);


/*
 * WARNING: DO NOT EDIT THIS FILE.
 * Changes to the script will be reset by future updates.
 * Set up custom cron executions by copying this file to a new filename.
 * Eg.
 * File: /modules/core/cron_x.php
 * Usage:  /usr/local/bin/php -q /home/YOUR_USERNAME/public_html/modules/core/cron_x.php
 *
 * Execution examples below.
 */



/*
 * EXECUTE CRON JOBS ONLY
 */

//Core_Cron::$cronjob_batch_size = 10;
//Core_Cron::$cronjob_batch_shuffle = false;
//Core_Cron::$tracelog_events = true;
//$process_tabs = false;
//$process_que = true;
//Core_Cron::execute_cron($process_tabs, $process_que);


/*
 * EXECUTE CRON JOBS IN SPECIFIC QUE NAME
 */

//Core_Cron::$cronjob_batch_size = 100;
//Core_Cron::$cronjob_batch_shuffle = true;
//Core_Cron::$tracelog_events = true;
//$process_tabs = false;
//$process_que = 'notifications';
//Core_Cron::execute_cron($process_tabs, $process_que);


/*
 * EXECUTE CRON TAB ONLY
 */

//Core_Cron::$tracelog_events = true;
//$process_tabs = true;
//$process_jobs = false;
//Core_Cron::execute_cron($process_tabs, $process_jobs);